### PR TITLE
NixOS Support

### PR DESCRIPTION
**Pull request by 6AA4FD**
Added NixOS support and documentation.

### CODE REVIEW

**Comment by 6AA4FD** [comment]
Additionally, is there any interest in a way to automatically run this with the choices pre-filled?

**Comment by mmcar** [comment]
I'm interested in automatically choosing Slippi versions, sounds like a nice feature.

**Comment by 6AA4FD** [comment]
The author hasn't reviewed or otherwise responded to the issue, so it probably won't happen here, sorry. I would recommend opening a separate issue if you want that.

**Comment by NikhilNarayana** [comment]
closing because this repo is unused now.

**Pull request closed without merging**
